title: Stackbit Starter Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
header:
  title: Ido
  has_nav: true
  nav_links:
    - label: Login
      url: 'https://idoapp.com.br/idoapp/'
      style: primary
      new_window: true
      no_follow: false
      type: action
  logo: images/Ido-Azul.png
footer:
  has_nav: true
  nav_links:
    - label: Fale conosco
      url: /contact
      style: link
    - label: Termos e Privacidade
      url: /terms
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: link
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: link
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: link
      new_window: true
  content: Este site foi criado por LeGData para IdoApp.
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://idoapp-62f1e.netlify.app'
